[package]
name = "pmetra_internal"
version = "0.1.0"
edition = "2021"
authors = ["Nilay Savant"]
description = "Internal crate for bevy_pmetra: Interactive Parametric Modelling for Bevy using Truck CAD kernel."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_pbr",
    "bevy_render",
    "bevy_text",
    "bevy_ui",
    "multi-threaded",
    "bevy_gizmos",
    "default_font",
] }
anyhow = "1.0"
strum = { version = "0.25", features = ["derive"] }
lazy_static = "1.4"
# picking
bevy_mod_picking = "0.18"
# truck stuff
truck-modeling = { git = "https://github.com/nilaysavant/truck.git", tag = "pmetra.v0.1.0" }
truck-shapeops = { git = "https://github.com/nilaysavant/truck.git", tag = "pmetra.v0.1.0" }
truck-meshalgo = { git = "https://github.com/nilaysavant/truck.git", tag = "pmetra.v0.1.0" }
truck-topology = { git = "https://github.com/nilaysavant/truck.git", tag = "pmetra.v0.1.0" }
truck-base = { git = "https://github.com/nilaysavant/truck.git", tag = "pmetra.v0.1.0" }
# truck deps for custom adaptation...
rustc-hash = "1.1.0"
# async
bevy_async_task = "0.1.0"
