[package]
name = "pmetra_demo"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
dev = ["bevy/dynamic_linking", "bevy/trace", "bevy/file_watcher"]

[dependencies]
bevy = "0.15"
bevy_rapier3d = "0.27"
smooth-bevy-cameras = "0.13"
bevy_egui = "0.33"
bevy-inspector-egui = "0.30"
strum = { version = "0.25", features = ["derive"] }
itertools = "0.12"
# gltf exporter
gltf = { version = "1.3", features = [
    "extras",
    "image",
    "KHR_texture_transform",
    "KHR_materials_specular",
    "KHR_materials_variants",
    "KHR_materials_unlit",
    "KHR_lights_punctual",
    "KHR_materials_pbrSpecularGlossiness",
    "KHR_materials_volume",
    "KHR_materials_ior",
    "KHR_materials_transmission",
    "guess_mime_type",
] }
image = "0.24"
base64 = "0.21"
# workspace crates...
bevy_pmetra = { path = "../" }
