[package]
name = "pmetra_demo"
version = "0.2.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
dev = ["bevy/dynamic_linking", "bevy/trace", "bevy/file_watcher"]

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_state",
    "bevy_color",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "multi_threaded",
    "png",
    "hdr",
    "x11",
    "bevy_gizmos",
    "tonemapping_luts",
    "smaa_luts",
    "default_font",
    "webgl2",
    "sysinfo_plugin",
] }
bevy_asset_loader = { version = "0.21", features = ["3d", "progress_tracking"] }
iyes_progress = "0.12"
bevy_rapier3d = "0.27"
anyhow = "1.0"
# smooth-bevy-cameras = "0.11" // Use the git version for now as crate is not updated. As below.
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras", rev = "414fa90d1f0c4a95efbaa5f5cf5839b5c904966d" }
bevy_egui = "0.28"
bevy-inspector-egui = "0.25"
strum = { version = "0.25", features = ["derive"] }
itertools = "0.12"
noise = "0.8"
futures-lite = "2.1"
lazy_static = "1.4"
# gltf exporter
gltf = { version = "1.3", features = [
    "extras",
    "image",
    "KHR_texture_transform",
    "KHR_materials_specular",
    "KHR_materials_variants",
    "KHR_materials_unlit",
    "KHR_lights_punctual",
    "KHR_materials_pbrSpecularGlossiness",
    "KHR_materials_volume",
    "KHR_materials_ior",
    "KHR_materials_transmission",
    "guess_mime_type",
] }
image = "0.24"
base64 = "0.21"
# workspace crates...
bevy_pmetra = { path = "../" }
